

export interface Municipality {
  id:   number;
  name: string;
}

export const MUNICIPALITIES: Municipality[] = [
  { id: 1,   name: "Abejorral" },
  { id: 2,   name: "Abriaquí" },
  { id: 3,   name: "Alejandría" },
  { id: 4,   name: "Amagá" },
  { id: 5,   name: "Amalfi" },
  { id: 6,   name: "Andes" },
  { id: 7,   name: "Angelópolis" },
  { id: 8,   name: "Angostura" },
  { id: 9,   name: "Anorí" },
  { id: 10,  name: "Anzá" },
  { id: 11,  name: "Apartadó" },
  { id: 12,  name: "Arboletes" },
  { id: 13,  name: "Argelia" },
  { id: 14,  name: "Armenia" },
  { id: 15,  name: "Barbosa" },
  { id: 16,  name: "Bello" },
  { id: 17,  name: "Belmira" },
  { id: 18,  name: "Betania" },
  { id: 19,  name: "Betulia" },
  { id: 20,  name: "Briceño" },
  { id: 21,  name: "Buriticá" },
  { id: 22,  name: "Cáceres" },
  { id: 23,  name: "Caicedo" },
  { id: 24,  name: "Caldas" },
  { id: 25,  name: "Campamento" },
  { id: 26,  name: "Cañasgordas" },
  { id: 27,  name: "Caracolí" },
  { id: 28,  name: "Caramanta" },
  { id: 29,  name: "Carepa" },
  { id: 30,  name: "Carmen de Viboral" },
  { id: 31,  name: "Carolina" },
  { id: 32,  name: "Caucasia" },
  { id: 33,  name: "Chigorodó" },
  { id: 34,  name: "Cisneros" },
  { id: 35,  name: "Ciudad Bolívar" },
  { id: 36,  name: "Cocorná" },
  { id: 37,  name: "Concepción" },
  { id: 38,  name: "Concordia" },
  { id: 39,  name: "Copacabana" },
  { id: 40,  name: "Dabeiba" },
  { id: 41,  name: "Donmatías" },
  { id: 42,  name: "Ebéjico" },
  { id: 43,  name: "El Bagre" },
  { id: 44,  name: "El Carmen de Viboral" },
  { id: 45,  name: "Entrerríos" },
  { id: 46,  name: "Envigado" },
  { id: 47,  name: "Fredonia" },
  { id: 48,  name: "Frontino" },
  { id: 49,  name: "Giraldo" },
  { id: 50,  name: "Girardota" },
  { id: 51,  name: "Gómez Plata" },
  { id: 52,  name: "Granada" },
  { id: 53,  name: "Guadalupe" },
  { id: 54,  name: "Guarne" },
  { id: 55,  name: "Guatapé" },
  { id: 56,  name: "Heliconia" },
  { id: 57,  name: "Hispania" },
  { id: 58,  name: "Itagüí" },
  { id: 59,  name: "Ituango" },
  { id: 60,  name: "Jardín" },
  { id: 61,  name: "Jericó" },
  { id: 62,  name: "La Ceja" },
  { id: 63,  name: "La Estrella" },
  { id: 64,  name: "La Pintada" },
  { id: 65,  name: "La Unión" },
  { id: 66,  name: "Liborina" },
  { id: 67,  name: "Maceo" },
  { id: 68,  name: "Marinilla" },
  { id: 69,  name: "Medellín" },
  { id: 70,  name: "Montebello" },
  { id: 71,  name: "Murindó" },
  { id: 72,  name: "Mutatá" },
  { id: 73,  name: "Nariño" },
  { id: 74,  name: "Nechí" },
  { id: 75,  name: "Necoclí" },
  { id: 76,  name: "Olaya" },
  { id: 77,  name: "Peñol" },
  { id: 78,  name: "Peque" },
  { id: 79,  name: "Pueblorrico" },
  { id: 80,  name: "Puerto Berrío" },
  { id: 81,  name: "Puerto Nare" },
  { id: 82,  name: "Puerto Triunfo" },
  { id: 83,  name: "Remedios" },
  { id: 84,  name: "Rionegro" },
  { id: 85,  name: "Sabanalarga" },
  { id: 86,  name: "Sabaneta" },
  { id: 87,  name: "Salgar" },
  { id: 88,  name: "San Andrés de Cuerquia" },
  { id: 89,  name: "San Carlos" },
  { id: 90,  name: "San Francisco" },
  { id: 91,  name: "San Jerónimo" },
  { id: 92,  name: "San José de la Montaña" },
  { id: 93,  name: "San Juan de Urabá" },
  { id: 94,  name: "San Luis" },
  { id: 95,  name: "San Pedro de los Milagros" },
  { id: 96,  name: "San Pedro de Urabá" },
  { id: 97,  name: "San Rafael" },
  { id: 98,  name: "San Roque" },
  { id: 99,  name: "San Vicente" },
  { id: 100, name: "Santa Bárbara" },
  { id: 101, name: "Santa Fe de Antioquia" },
  { id: 102, name: "Santa Rosa de Osos" },
  { id: 103, name: "Santo Domingo" },
  { id: 104, name: "El Santuario" },
  { id: 105, name: "Segovia" },
  { id: 106, name: "Sonson" },
  { id: 107, name: "Sopetrán" },
  { id: 108, name: "Támesis" },
  { id: 109, name: "Tarazá" },
  { id: 110, name: "Tarso" },
  { id: 111, name: "Titiribí" },
  { id: 112, name: "Toledo" },
  { id: 113, name: "Turbo" },
  { id: 114, name: "Uramita" },
  { id: 115, name: "Urrao" },
  { id: 116, name: "Valdivia" },
  { id: 117, name: "Valparaíso" },
  { id: 118, name: "Vegachí" },
  { id: 119, name: "Venecia" },
  { id: 120, name: "Vigía del Fuerte" },
  { id: 121, name: "Yalí" },
  { id: 122, name: "Yarumal" },
  { id: 123, name: "Yolombó" },
  { id: 124, name: "Yondó" },
  { id: 125, name: "Zaragoza" }
]

